
apiVersion: apps/v1
kind: Deployment
metadata:
  name: agribrain-interview
  labels:
    app: interview
spec:
  replicas: 1
  selector:
    matchLabels:
      app: interview
  template:
    metadata:
      labels:
        app: interview
    spec:
      containers:
      - name: agribrain-interview
        image: gcr.io/agribrain/interview-webapp:latest
        ports:
        - containerPort: 8501
